name: Auto-Merge master to asia

on:
  push:
    branches:
      - master

jobs:
  merge_master_to_asia:
    runs-on: ubuntu-latest
    environment: Hatcher+ FAAST
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.HATCHER_PLUS_APP_ID }}
          private-key: ${{ secrets.HATCHER_PLUS_APP_SECRET }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase false  # Ensures merge strategy

      - name: Update Local Master Branch
        run: |
          git checkout master
          git pull origin master

      - name: Create PR and Handle Merge Conflicts
        id: create_pr
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          BRANCH_NAME="auto-merge-master-to-asia-$(date +%Y%m%d%H%M%S)"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT
          
          # Create and switch to the new branch based on 'asia'
          git checkout -b $BRANCH_NAME origin/asia
          
          # Merge 'master' into the new branch
          if git merge master --no-commit --no-ff; then
            echo "No merge conflicts detected"
            git commit -m "Auto-merged master into asia"
            CONFLICTS=false
          else
            echo "Merge conflicts detected"
            git merge --abort
            CONFLICTS=true
          fi
          
          git push origin $BRANCH_NAME
          
          if [ "$CONFLICTS" = true ]; then
            PR_TITLE="[Needs Review] Auto-Merge master to asia"
            PR_BODY="This pull request is automatically created to merge changes from master to asia. **Merge conflicts detected. Manual review required.**"
          else
            PR_TITLE="Auto-Merge master to asia"
            PR_BODY="This pull request is automatically created to merge changes from master to asia."
          fi

          PR_URL=$(gh pr create --title "$PR_TITLE" \
                                --body "$PR_BODY" \
                                --base asia \
                                --head $BRANCH_NAME \
                                --reviewer "<REVIEWER_USERNAME>")
          
          echo "PR_URL=$PR_URL" >> $GITHUB_OUTPUT
          echo "Created PR: $PR_URL"

          if [ "$CONFLICTS" = false ]; then
            echo "Attempting to merge PR..."
            gh pr merge $PR_URL --squash --admin --delete-branch
          else
            echo "Merge conflicts detected. PR created for manual review."
          fi

      - name: Cleanup
        if: always()
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          BRANCH_NAME="${{ steps.create_pr.outputs.BRANCH_NAME }}"
          
          # Attempt to delete the branch locally and remotely, ignore errors
          git branch -D $BRANCH_NAME || true
          git push origin --delete $BRANCH_NAME || true
