name: Auto-Rebase master onto asia

on:
  push:
    branches:
      - master

jobs:
  rebase_master_onto_asia:
    runs-on: ubuntu-latest
    environment: Hatcher+ FAAST
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.HATCHER_PLUS_APP_ID }}
          private-key: ${{ secrets.HATCHER_PLUS_APP_SECRET }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Rebase asia onto master
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          # Checkout the asia branch
          git checkout asia
          
          # Rebase asia onto master
          if git rebase origin/master; then
            echo "Rebase successful"
            CONFLICTS=false
          else
            echo "Rebase conflicts detected"
            git rebase --abort
            CONFLICTS=true
          fi

      - name: Push changes if rebase successful
        if: success()
        run: |
          if [ "$CONFLICTS" = false ]; then
            git push origin asia --force-with-lease
            echo "Rebase completed and pushed to asia"
          else
            echo "Rebase failed due to conflicts, no changes were pushed"
            exit 1
          fi

      - name: Clean up
        if: always()
        run: |
          echo "Clean up completed"
