name: Auto-Merge master to asia

on:
  push:
    branches:
      - master

jobs:
  merge_master_to_asia:
    runs-on: ubuntu-latest
    environment: Hatcher+ FAAST
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.HATCHER_PLUS_APP_ID }}
          private-key: ${{ secrets.HATCHER_PLUS_APP_SECRET }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and merge PR
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          BRANCH_NAME="auto-merge-master-to-asia-$(date +%Y%m%d%H%M%S)"
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME

          PR_URL=$(gh pr create --title "Auto-Merge master to asia" \
                                --body "This pull request is automatically created to merge changes from master to asia" \
                                --base asia \
                                --head $BRANCH_NAME)

          echo "Created PR: $PR_URL"

          if gh pr checks $PR_URL; then
            echo "Checks found, waiting for completion..."
            gh pr checks $PR_URL --watch
            if gh pr checks $PR_URL; then
              echo "Checks passed, merging PR"
              gh pr merge $PR_URL --squash --admin
            else
              echo "Checks failed, PR was not merged"
              exit 1
            fi
          else
            echo "No checks found, merging PR immediately"
            gh pr merge $PR_URL --squash --admin
          fi

      - name: Clean up
        if: always()
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          BRANCH_NAME="auto-merge-master-to-asia-$(date +%Y%m%d%H%M%S)"
          
          # Try to delete the branch, ignoring errors
          git push origin --delete $BRANCH_NAME || true
