name: Update Shrinkwrap

on:
  push:
    branches:
      - master

jobs:
  generate-shrinkwrap:
    runs-on: ubuntu-latest
    environment: Hatcher+ FAAST
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.HATCHER_PLUS_APP_ID }}
          private-key: ${{ secrets.HATCHER_PLUS_APP_SECRET }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate shrinkwrap file
        run: npm shrinkwrap

      - name: Create and Auto-Merge Pull Request
        id: create_pr
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Generate a unique branch name
          BRANCH_NAME="update-shrinkwrap-$(date +%Y%m%d%H%M%S)"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT
          
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "Update shrinkwrap file"
          git push origin $BRANCH_NAME

          PR_URL=$(gh pr create --title "Update shrinkwrap file" \
                                --body "Automatically generated PR to update the shrinkwrap file" \
                                --base master \
                                --head $BRANCH_NAME)

          echo "PR_URL=$PR_URL" >> $GITHUB_OUTPUT
          
          # Enable auto-merge
          gh pr merge $PR_URL --auto --merge

          # Check if there are any checks
          if gh pr checks $PR_URL; then
            echo "Checks found, waiting for completion..."
            gh pr checks $PR_URL --watch
          else
            echo "No checks found, PR will be merged automatically when possible"
          fi

      - name: Check PR status and clean up
        if: always()
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          BRANCH_NAME="${{ steps.create_pr.outputs.BRANCH_NAME }}"
          PR_URL="${{ steps.create_pr.outputs.PR_URL }}"
          
          # Check PR status
          PR_STATE=$(gh pr view $PR_URL --json state --jq .state)
          
          if [ "$PR_STATE" = "MERGED" ]; then
            echo "PR was merged successfully"
          elif [ "$PR_STATE" = "OPEN" ]; then
            echo "PR is still open, it will be merged automatically when checks pass"
          else
            echo "PR is in unexpected state: $PR_STATE"
            gh pr close $PR_URL
            git push origin --delete $BRANCH_NAME
          fi
